name: Docker Image CI

on:
  push:
    branches:
      - v2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: hub.cloud.philipplentzen.dev
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: hub.cloud.philipplentzen.dev/philipplentzen:latest, hub.cloud.philipplentzen.dev/philipplentzen:${{ github.sha }}
