name: 🧪 Tests
on:
  pull_request:

jobs:
  playwright:
    name: 🎭 e2e
    runs-on: ubuntu-latest
    env:
      TURBO_API: ${{ secrets.TURBO_API }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    container:
      image: mcr.microsoft.com/playwright:v1.58.0-noble
      options: --user 1001
    steps:
      - name: 🔍 Verify Environment
        shell: bash
        run: |
          echo "TURBO_API: $TURBO_API"
          echo "TURBO_TEAM: $TURBO_TEAM"
          if [ -n "$TURBO_TOKEN" ]; then
            echo "TURBO_TOKEN is set (length: ${#TURBO_TOKEN})"
          else
            echo "TURBO_TOKEN IS NOT SET"
          fi
      - name: 🚚 Checkout
        uses: actions/checkout@v6

      - name: 🛠️ Setup
        uses: ./.github/actions/setup

      - name: 🎭 Run e2e tests
        run: pnpm run e2e

      - uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: apps/philipplentzen/playwright-report/
          retention-days: 30