name: 🧪 Tests
on:
  pull_request:

jobs:
  playwright:
    name: 🎭 e2e
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.57.0-noble
    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v5
      - name: 🛠️ Setup pnpm
        uses: pnpm/action-setup@v4
      - name: 🛠️ Use node.js
        uses: actions/setup-node@v5
        with:
          cache: "pnpm"
      - name: 📦 Install dependencies
        run: pnpm install
      - name: 🎭 Run e2e tests
        run: pnpm run e2e