name: 📸 Update Snapshots
on:
  issue_comment:
    types:
      - created

jobs:
  update:
    name: 📸 Update Snapshots
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, 'update snapshots') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    container:
      image: mcr.microsoft.com/playwright:v1.57.0-noble
      options: --user 1001
    steps:
      - name: 👀 Acknowledge Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl --request POST \
            --url "https://api.github.com/repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }}/reactions" \
            --header "Authorization: Bearer $GH_TOKEN" \
            --header "Accept: application/vnd.github+json" \
            --data '{"content":"+1"}'

      - name: 🔍 Get PR Details
        uses: octokit/request-action@v2.x
        id: get_pr_data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: GET /repos/{owner}/{repo}/pulls/{pull_number}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pull_number: ${{ github.event.issue.number }}

      - name: 🚚 Checkout
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: refs/pull/${{ github.event.issue.number }}/head

      - name: 🛠️ Setup
        uses: ./.github/actions/setup

      - name: 📸 Update Snapshots
        run: pnpm run e2e -- --update-snapshots

      - name: 🔄 Commit and Push Changes
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_BRANCH: ${{ fromJson(steps.get_pr_data.outputs.data).head.ref }}
        shell: bash
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m "chore: update playwright snapshots"
            git push origin HEAD:refs/heads/$TARGET_BRANCH
          
            curl --request POST \
              --url "https://api.github.com/repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }}/reactions" \
              --header "Authorization: Bearer $GH_TOKEN" \
              --header "Accept: application/vnd.github+json" \
              --data '{"content":"rocket"}'
          else
            curl --request POST \
              --url "https://api.github.com/repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }}/reactions" \
              --header "Authorization: Bearer $GH_TOKEN" \
              --header "Accept: application/vnd.github+json" \
              --data '{"content":"eyes"}'
          fi
      - name: ❌ Notify Failure
        if: failure()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl --request POST \
            --url "https://api.github.com/repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }}/reactions" \
            --header "Authorization: Bearer $GH_TOKEN" \
            --header "Accept: application/vnd.github+json" \
            --data '{"content":"confused"}'
